_wandb:
    value:
        cli_version: 0.21.4
        e:
            xidh2xv1gfg88a6ul8kkq56h7gz6okb1:
                args:
                    - --input_data
                    - ../Data/Pretrain/sal-lps-150-1500(labeled)_data.npy
                    - --input_lables
                    - ../Data/Pretrain/sal-lps-150-1500(labeled)_labels.npy
                    - --output
                    - ../Output/NMF
                    - --nmf_encoder
                    - ../Models/NMF/hiv-cancer_nmf_model.joblib
                    - --name
                    - nmf-classifier
                codePath: src/ClassifierNMF.py
                codePathLocal: ClassifierNMF.py
                cpu_count: 14
                cpu_count_logical: 28
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "501809635328"
                        used: "101699653632"
                email: mazaruratapiwa03@gmail.com
                executable: /home-mscluster/tmazarura/miniconda3/bin/python
                git:
                    commit: 567067e3eb58e06e10cdfe4a148879795ecc4f6d
                    remote: git@github.com:Tapiwamaz/HonoursResearch.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-159f1622-063e-dba8-83e3-a387f692ea19
                host: mscluster53.ms.wits.ac.za
                memory:
                    total: "134775623680"
                os: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
                program: /home-mscluster/tmazarura/HonoursResearch/src/ClassifierNMF.py
                python: CPython 3.13.5
                root: /home-mscluster/tmazarura/HonoursResearch/src
                slurm:
                    cluster_name: mscluster
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "28"
                    cpus_per_task: "16"
                    gtids: "0"
                    job_account: students
                    job_cpus_per_node: "28"
                    job_gid: "21083"
                    job_id: "156193"
                    job_name: ClassifierNMF
                    job_nodelist: mscluster53
                    job_num_nodes: "1"
                    job_partition: bigbatch
                    job_qos: normal
                    job_uid: "21083"
                    job_user: tmazarura
                    jobid: "156193"
                    localid: "0"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: mscluster53
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /home-mscluster/tmazarura/HonoursResearch/src
                    submit_host: mscluster-login1.ms.wits.ac.za
                    task_pid: "1998317"
                    tasks_per_node: "1"
                    topology_addr: mscluster53
                    topology_addr_pattern: node
                    working_cluster: mscluster:10.100.14.254:6817:9472:102
                startedAt: "2025-09-13T18:04:11.302450Z"
                writerId: xidh2xv1gfg88a6ul8kkq56h7gz6okb1
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "2": epoch/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.13.5
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 7
                - 16
                - 38
            "4": 3.13.5
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 32
dropout:
    value: 0.5
epochs:
    value: 50
hidden_size:
    value: 64
learning_rate:
    value: 0.001
loss:
    value: sparse_categorical_crossentropy
metric:
    value: accuracy
optimizer:
    value: adam
output_activation:
    value: softmax
